FROM registry.access.redhat.com/ubi9/nodejs-18

USER root

# Update base image for latest security updates
# (ubi images are not released that often)
RUN dnf -y  --setopt=tsflags=nodocs update && \
    dnf -y clean all --enablerepo='*'


RUN mkdir -p /opt/app-root/src/modules
RUN pwd

RUN ls -la

# Copying in source code
COPY --chown=1001:0 ./modules/* /opt/app-root/src/modules/
COPY --chown=1001:0 ./package*.json /opt/app-root/src/
COPY --chown=1001:0 ./index.js /opt/app-root/src/

#RUN 'mkdir -p /opt/app-root/src/{modules,framework,app}'
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN npm install && npm cache clean --force && npm install -g typescript
RUN pwd
RUN ls -la /opt/app-root/src/node_modules
CMD ["node", "./index.js"]

# RUN /usr/libexec/s2i/assemble
# # Run script sourced from builder image based on user input or image metadata.
# # If this file does not exist in the image, the build will fail.
# CMD /usr/libexec/s2i/run